name-template: 'OluKai Release Notes version: v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Exciting New Features 🎉'
    labels:
      - 'feature'
      - 'update'
  - title: 'Bug Fixes 🐛'
    labels:
      - 'bugfix'
      - 'fix'
  - title: 'Maintenance 🧰'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes
  $CHANGES
